# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('id_number', models.IntegerField(max_length=9)),
                ('address', models.CharField(max_length=70)),
                ('age', models.IntegerField(max_length=3)),
                ('data_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
