# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
