# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0002_auto_20161113_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='data_added',
        ),
        migrations.AddField(
            model_name='person',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
