# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0004_auto_20161113_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 11, 13, 19, 45, 41, 168475, tzinfo=utc)),
        ),
    ]
