# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0005_auto_20161113_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 7, 23, 44, 711713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
