# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Proj', '0006_auto_20161117_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 11, 17, 7, 35, 57, 531214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.IntegerField(max_length=9, unique=True),
        ),
    ]
